### ISSUE TITLE
Auth init failed

### ISSUE THREAD

**Issue by Giton22** [FlemingVincent/expo-supabase-starter#22]
Hey ,sometimes after reopen my application (dev build) the auth is not initialized on the first protected page (home for me). Sometimes also get the index page as not found loaded firstly. 

And also styles are incorrect sometimes:
![image](https://github.com/FlemingVincent/expo-supabase-starter/assets/24484823/c2aaa4b9-26c8-4e15-b862-f3a87c374e0a)
And this is how should look like:
![image](https://github.com/FlemingVincent/expo-supabase-starter/assets/24484823/30d62487-4ae1-4993-9f64-b13b71d976ca)

**Comment by FlemingVincent** [comment]
Hi, sorry to hear that! Can you include video's and a more detailed description?
