### ISSUE TITLE
Invalid Hook Call 

### ISSUE THREAD

**Issue by Rohit685** [FlemingVincent/expo-supabase-starter#23]
Hello. I tried running this app and edited nothing besides the Supabase url and API key. I got this error: 
`Invalid hook call. Hooks can only be called inside of the body of a function component.`

`This error is located at:
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by CssInterop.View)
    in CssInterop.View (created by AppContainer)
    in RCTView (created by CssInterop.View)
    in CssInterop.View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
 ERROR  TypeError: Cannot read property 'useMemo' of null`

Do you know a fix? Thanks

**Comment by FlemingVincent** [comment]
Hi @Rohit685, I just cloned the app, ran ```yarn install``` to install dependencies, and replaced the environment variables and I am having no issue getting the app running. Is there any way you could share your repository?

**Comment by Rohit685** [comment]
Just to confirm @FlemingVincent, there are only 2 environment variables which are the supabase api key and supabase url, correct?

**Comment by Rohit685** [comment]
I used npm but that shouldnt matter.

**Comment by FlemingVincent** [comment]
@Rohit685 Yes, those are the only two environment variables used in the application. And no, if you followed all of the instructions in the docs, everything should work.

**Comment by Rohit685** [comment]
Yea. It does not seem to work. The confusing thing is I did not find any usages of useMemo so I am confused on why it is not working.

**Comment by Rohit685** [comment]
It also gives me an invalid hook call:

` at RCTView
    at CssInterop.View (http://192.168.4.143:8081/node_modules%5Cexpo-router%5Centry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:11006:45)
    at RCTView
    at CssInterop.View (http://192.168.4.143:8081/node_modules%5Cexpo-router%5Centry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:11006:45)
    at AppContainer (http://192.168.4.143:8081/node_modules%5Cexpo-router%5Centry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:87024:36)
    at main(RootComponent) (http://192.168.4.143:8081/node_modules%5Cexpo-router%5Centry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:97817:28)      
 ERROR  Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:`

**Comment by FlemingVincent** [comment]
I would try recloning, using yarn, and seeing if you have any issues. I agree, using npm shouldn't matter, but for reproduction purposes it may help.

**Comment by Rohit685** [comment]
never knew using npm instead of yarn would make that much of a difference 😐

**Comment by FlemingVincent** [comment]
Yeah that's interesting... I was able to get it working with npm too, so I'm not sure.

**Comment by Rohit685** [comment]
Im mad now. I spent way too long trying to figure that one out for it to be that dumb.😂

**Comment by Rohit685** [comment]
> Yeah that's interesting... I was able to get it working with npm too, so I'm not sure.

Thank you for the response though. I appreciate it

**Comment by FlemingVincent** [comment]
Yeah no problem, thanks for using the project!
