### ISSUE TITLE
When I run npm install and then set my .env it immediately says unmatched route page could not be found

### ISSUE THREAD

**Issue by ajhous44** [flemingvincent/expo-supabase-starter#33]
I'm on windows. When I click sitemap it only shows (auth)_layout.tsx -> sign-up.tsx and when I click it it looks nothing like the demo video and has 0 styling.

**Comment by flemingvincent** [comment]
Hi @ajhous44, can you provide more context so that I can try to reproduce the issue? I've just cloned, set environment variables, and installed dependencies using NPM without any issues.
