### ISSUE TITLE
Question about existing code

### ISSUE THREAD

**Issue by Rohit685** [flemingvincent/expo-supabase-starter#36]
Whenever I use tailwind in a component, do I have to do:

```tsx
className={cn("text-blue-200")};
```

Do I have to do the cn() stuff?

All the styling im adding to the project only works when I save the file and doesnt work when I run the dev server initially and I am very confused.

**Comment by Rohit685** [comment]
Another issue is that the app does not update when I save the code....any fixes?

**Comment by flemingvincent** [comment]
Hi @Rohit685,

The short answer is no, you do not have to use the `className={cn("text-blue-200")}` notation.

Throughout the application, you will find that tailwind styles can be applied simply by using `className="text-blue-200"`.

The "cn() stuff" is a custom utility used to create more complex styles, which are more common in the styled reusable components, but can still be used in the application.

Regarding your second question about the app not updating when saving, I cannot say without looking at your code. Make sure you follow the instructions in [Application Overview](https://github.com/flemingvincent/expo-supabase-starter/blob/main/docs/application-overview.md) and there shouldn't be any issues.
