### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by rumfiske** [FlemingVincent/expo-supabase-starter#5]
Hot reload doesnt seem to be working on Android out of the box. What to do?

**Comment by FlemingVincent** [comment]
@rumfiske I am just now noticing this issue is also happening on iOS. I will begin looking into it, and implement a fix ASAP.

**Comment by FlemingVincent** [comment]
@rumfiske Should be good to go on iOS and Android!

**Comment by rumfiske** [comment]
Worked aften i deleted nodejs and removed the resolutions in package.json. not sure why, but multiple People have mentioned it on other sites. Thanks for quick response. Awesome repo, now making secound app with it :)

**Comment by FlemingVincent** [comment]
Thanks a lot! Glad to hear that you're enjoying using it!
