### ISSUE TITLE
Forget password

### ISSUE THREAD

**Issue by uskudaristanbul** [flemingvincent/expo-supabase-starter#59]
Hi, could you also develop forget password section if its possible for you? 
Kind regards

**Comment by flemingvincent** [comment]
Hi @uskudaristanbul,

Sorry, I am going to close this issue... There are a few different ways to handle "Forgot Password" functionality with Supabase (deep linking, OTP) and I believe it is best to allow developers to choose and implement their own solutions.

However, here is the documentation from Supabase's JavaScript API Reference for implementing "Forgot Password" functionality: https://supabase.com/docs/reference/javascript/auth-resetpasswordforemail
