### ISSUE TITLE
[HELP] - Auth screens and Blank screen.

### ISSUE THREAD

**Issue by rumfiske** [FlemingVincent/expo-supabase-starter#7]
**Issue 1:** If i go from route "/" to /login and use the native back button to the route "/" is just blank.

How i handle route change
```javascript
	<TouchableOpacity onPress={() => router.push("/login")}>
		<Text style={tw`muted text-center mt-4`}>
		Already have an account? {"\n"} Login
		</Text>
	</TouchableOpacity>
```

**Issue 2:** Only way i could make auth screens work, was to add segments as dependenci of the useEffect. Also when logged in, you can still go back to login screen. If you close the app and open it again, it will fast flash the login screen, before going to home screen.

**/app/_layout.tsx**
``` javascript
	useEffect(() => {
		if (!initialized) return;

		// Check if the path/url is in the (auth) group
		const inAuthGroup = segments[0] === "(auth)";

		if (session && !inAuthGroup) {
			// Redirect authenticated users to the home page
			router.replace("/home");
		} else if (!session && inAuthGroup) {
			// Redirect unauthenticated users to the sign up page
			router.replace("/");
		}

		console.log(
			"currentRoute",
			currentRoute,
			"inAuthGroup" + "\n",
			inAuthGroup,
		);
	}, [session, initialized, segments]);
```

There is also flickering when navigating between screens

File structure
![NVIDIA_Share_tjczRRZpei](https://github.com/FlemingVincent/expo-supabase-starter/assets/59709554/bc89fd9c-e872-47ae-b726-b786185795ea)

(UPDATE)
Expo-blur causes screens to flick and nor work correctly.

**Comment by FlemingVincent** [comment]
@rumfiske Sorry for the late response, I am currently improving/simplifying the authentication flow, which should fix these issues.

**Comment by FlemingVincent** [comment]
@rumfiske I just merged [#8 Update authentication flow and functionality.](https://github.com/FlemingVincent/expo-supabase-starter/pull/8) This includes an improved authentication flow, which more closely resembles the starting template provided by Expo.

**Comment by rumfiske** [comment]
Thank you! :) No problem! I fixed it myself, but awesome you implemented the changes here aswell.

Will you update to SDK 50 when it releases?

**Comment by FlemingVincent** [comment]
@rumfiske Yes I will
